### ISSUE TITLE
SVGO Vulnerability in 1.x / Dropped support for importing SVG Fonts?

### ISSUE THREAD

**Issue by bwhite94** [iconify/tools#17]
We are seeing vulnerabilities in 1.3.18 for SVGO and that is the last published version with `ImportFont` which we are currently utilizing. See `CVE-2021-33587` for more info.

In the move from 1.x to 2.x it appears the `ImportFont` functionality (as referenced in the 1.x docs [here](https://docs.iconify.design/tools/node/import-font.html) was removed.

Is there an alternative way to import fonts in 2.x or is this support being dropped?

**Comment by cyberalien** [comment]
It was dropped and is not coming back.

Biggest issue is third party software it relied on is no longer maintained. Import function relied on importing from SVG font, which has been dropped by pretty much everyone. Cropping function relied on headless browser that no longer exists.

Second issue is icon fonts are almost always really bad. Icons imported from fonts are designed to work only in those fonts, they aren't aligned correctly when used as SVG. Bounding boxes for glyphs are more like suggestions rather than actual icon boxes, which required cropping function to import icon properly, which no longer works.

Old icon sets available in Iconify that are imported from fonts are kept as is, but no new icon sets will be imported because those icons look terrible when used as SVG, so import function is no longer used and will not be rewritten.

**Comment by bwhite94** [comment]
Thanks @cyberalien for the fast response! For now we will force resolutions for SVGO to remediated versions to continue using 1.3.18 and plan to convert our SVG font to individual SVG files and update our import scripts to use the import directory functions outlined [here](https://docs.iconify.design/tools/tools2/import/directory.html).

**Comment by cyberalien** [comment]
Looking at vulnerability you've mentioned, parsing SVG fonts is not affected by it. It applies to parsing stylesheets, which are not present in fonts, so you can ignore it.

Unfortunately I can't help with this issue. Adding similar function to new version of tools would require a lot of development, but I can barely keep up with other parts of Iconify project, so there is no time for that.

**Comment by bwhite94** [comment]
No worries, my apologies as I thought I closed this with my last comment. Thanks again for your quick responses and dedication to a great tool as always!
